# Generated by Django 4.2.2 on 2023-07-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_details_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_details',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
